### ISSUE TITLE
please add suport for IDN domain names

### ISSUE THREAD

**Issue by novia713** [urbanadventurer/WhatWeb#102]
currently i get this for my domain www.reseñas.li
→
ERROR: Socket error Hostname not known: rese%C3%B1as.li

:-(

**Comment by urbanadventurer** [comment]
Fixed in 0.5.0-dev.
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/101783/33487573-f2bfbb06-d6ad-11e7-9890-888ebee16d2c.png">
