### ISSUE TITLE
Unable to initialize whatweb in Cygwin on Windows 7

### ISSUE THREAD

**Issue by nipuncodestoo** [urbanadventurer/WhatWeb#104]
$ ./whatweb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will be de                                                                                                                                                                                               precated in the future, use String#encode instead.
NOTE: Gem.available? is deprecated, use Specification::find_by_name. It will be                                                                                                                                                                                                removed on or after 2011-11-01.
Gem.available? called from ./whatweb:55.
NOTE: Gem.available? is deprecated, use Specification::find_by_name. It will be                                                                                                                                                                                                removed on or after 2011-11-01.
Gem.available? called from ./whatweb:66.
NOTE: Gem.available? is deprecated, use Specification::find_by_name. It will be                                                                                                                                                                                                removed on or after 2011-11-01.
Gem.available? called from ./whatweb:76.
NOTE: Gem.available? is deprecated, use Specification::find_by_name. It will be                                                                                                                                                                                                removed on or after 2011-11-01.
Gem.available? called from ./whatweb:86.
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /directory/whatweb-0.4.7.tar/whatweb-0.4.7/lib/tld.rb:76: invalid mult                                                                                                                                                                                               ibyte char (US-ASCII) (SyntaxError)
/directory/whatweb-0.4.7.tar/whatweb-0.4.7/lib/tld.rb:                                                                                                                                                                                               76: invalid multibyte char (US-ASCII)
/directory/whatweb-0.4.7.tar/whatweb-0.4.7/lib/tld.rb:                                                                                                                                                                                               76: syntax error, unexpected $end, expecting '}'
...stration"=>false,"country"=>"Åland Islands","slds"=>[]},
...                               ^
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from ./whatweb:117:in `<main>'

This happens after I specifically installed all dependencies. Can you help please ?

**Comment by urbanadventurer** [comment]
Issue already solved. This was a ruby 1.9.x issue
