### ISSUE TITLE
Update Google-Maps.rb plugin with Geo Sensor parameter

### ISSUE THREAD

**Issue by pvdl** [urbanadventurer/WhatWeb#108]
Maybe it is an idea to upgrade the existing Google-Maps plugin with a Geo Sensor detection.
More info here: https://developers.google.com/maps/articles/geolocation
Module: Geo Sensor
String: sensor=true | sensor=false

Making of an extra plugin for this topic is also an option.

**Comment by urbanadventurer** [comment]
The sensor parameter is now deprecated by Google Maps
