### ISSUE TITLE
Failed to detect Character set and log to MongoDB

### ISSUE THREAD

**Issue by loveshell** [urbanadventurer/WhatWeb#115]
root@bt:~/WhatWeb-master# ruby1.8 whatweb www.baidu.com  --log-mongo-host localhost --log-mongo-database scanning --log-mongo-collection australia 
MongoDB logging requires the Charset plugin to be activated. The Charset plugin is the slowest whatweb plugin, it not included by default, and resides in the plugins-disabled folder. Use ./whatweb -p +./plugins-disabled/Charset.rb to enable it.

root@bt:~/WhatWeb-master# ruby1.8 whatweb www.baidu.com  --log-mongo-host localhost --log-mongo-database scanning --log-mongo-collection australia  -p +./plugins-disabled/Charset.rb
http://www.baidu.com [200] Charset[Failed], Cookies[BAIDUID,BDSVRTM,H_PS_PSSID], Country[CHINA][CN], HTML5, HTTPServer[BWS/1.0], IP[115.239.210.26], Script[text/javascript], Title[百度一下，你就知道], UncommonHeaders[bdqid,bdpagetype,bduserid]
http://www.baidu.com: Failed to detect Character set and log to MongoDB

root@bt:~/WhatWeb-master# ruby1.8 whatweb www.paypal.com  --log-mongo-host localhost --log-mongo-database scanning --log-mongo-collection australia  -p +./plugins-disabled/Charset.rb
http://www.paypal.com [302] Akamai-Global-Host, Charset[Failed], Country[UNITED STATES][US], HTTPServer[AkamaiGHost], IP[23.41.66.234], RedirectLocation[https://www.paypal.com/]
http://www.paypal.com: Failed to detect Character set and log to MongoDB
https://www.paypal.com/ [301] Apache, Charset[Failed], Cookies[Apache,DC,KHcl0EuY7AKSMgfvHl7J5E7hPtK,X-PP-SILOVER,aksession,cookie_check,cwrClyrK4LoCV1fydGbAxiNL6iG], Country[UNITED STATES][US], HTTPServer[Apache], HttpOnly[KHcl0EuY7AKSMgfvHl7J5E7hPtK,X-PP-SILOVER,cookie_check,cwrClyrK4LoCV1fydGbAxiNL6iG], IP[23.41.66.234], RedirectLocation[https://www.paypal.com/c2], UncommonHeaders[strict-transport-security,dc], X-Frame-Options[SAMEORIGIN]
https://www.paypal.com/: Failed to detect Character set and log to MongoDB
https://www.paypal.com/c2 [301] Akamai-Global-Host, Charset[Failed], Cookies[aksession], Country[UNITED STATES][US], HTTPServer[AkamaiGHost], IP[23.41.66.234], RedirectLocation[https://www.paypal.com/c2/webapps/mpp/home]
https://www.paypal.com/c2: Failed to detect Character set and log to MongoDB
https://www.paypal.com/c2/webapps/mpp/home [200] Apache, Charset[Failed], Cookies[Apache,DC,SPARTAJSESSIONID,SPARTAJSESSIONIDV2,X-PP-SILOVER,aksession,analytics,consumer_display,cookie_check], Country[UNITED STATES][US], HTML5, HTTPServer[Apache], HttpOnly[SPARTAJSESSIONID,SPARTAJSESSIONIDV2,X-PP-SILOVER,analytics,consumer_display,cookie_check], IP[23.41.66.234], PasswordField[login_password], Script[text/javascript], Title[%0D%0A%09%09%0D%0A%09%09%09 Send Money, Pay Online and Merchant Accounts - PayPal China%0D%0A%09%09%0D%0A%09%09], UncommonHeaders[strict-transport-security,dc], X-Frame-Options[SAMEORIGIN], X-UA-Compatible[IE=9]
https://www.paypal.com/c2/webapps/mpp/home: Failed to detect Character set and log to MongoDB

**Comment by urbanadventurer** [comment]
The Charset plugin works now with Ruby 2.x and Ruby 1.9.x

http://www.baidu.com [200] Charset[UTF-8], Cookies[BAIDUID,BDSVRTM,BD_HOME,BIDUPSID,H_PS_PSSID,PSTM], HTML5, HTTPServer[BWS/1.1], IP[103.235.46.39], JQuery, Meta-Refresh-Redirect[/baidu.html?from=noscript], OpenSearch[/content-search.xml], Script[text/javascript], Title[百度一下，你就知道], UncommonHeaders[cxy_all,bdpagetype,bdqid,bduserid], X-Powered-By[HPHP], X-UA-Compatible[IE=Edge,IE=Edge,chrome=1]
