### ISSUE TITLE
Running in OS X 10.9

### ISSUE THREAD

**Issue by darksheer** [urbanadventurer/WhatWeb#116]
Trying to run Whatweb with all extra dep gems installed:

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require': cannot load such file -- md5 (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
	from whatweb:55:in `<main>'

Not sure really where to start investigation this.

**Comment by urbanadventurer** [comment]
This was fixed by andrericardo
