### ISSUE TITLE
new feature: read cookies from a file

### ISSUE THREAD

**Issue by blshkv** [urbanadventurer/WhatWeb#139]
It's hard to submit multiple cookie values into the command line. It would be good to have a feature which would allow to read it from a file. Netscape file format would do it.

Thanks.

**Comment by urbanadventurer** [comment]
Thanks for the suggestion. This is now implemented in version 0.5.0-dev but in a document.cookie format.

**Comment by blshkv** [comment]
Honestly, i forgot about thia request and th reason why i need it. But hey, it's better late then never :)
