### ISSUE TITLE
JSON log: should be a list of hash

### ISSUE THREAD

**Issue by cjeanneret** [urbanadventurer/WhatWeb#151]
Hello,

While testing the JSON output, it seems the generated JSON isn't fully correct: when there are redirects, it has multiple hashes, but NOT in the form of a list. It should be something like:
```JSON
[
{ "target": "foo", "and":"so on" },
{ "target": "redirect 1", "and":"so on" },
{ "target": "redirect 2", "and":"so on" },
{ "target": "redirect 3", "and":"so on" }
]
```

This would allow us to parse the JSON later with some script and, for example, directly jump to the latest target in case of multiple redirects.

Thank you!

**Comment by urbanadventurer** [comment]
This issue is now fixed.
