### ISSUE TITLE
can not connect to mongodb

### ISSUE THREAD

**Issue by sinme** [urbanadventurer/WhatWeb#168]
###mongo version cause this bug?
sorry,my English is poor.i try my best to explain this question
```
//i have install below software
rvm install 1.9.3
yum  -y  install rubygems
yum  -y install ruby-devel
gem install em-resolv-replace
gem install json
gem install bson_ext
gem install mongo
gem install rchardet

//then test on two  centos  server( x64 and x86 centos ).but meet the same bug
[root@cluster whatweb]#  ruby -v
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
[root@cluster whatweb]# ps -aux |grep mongo
Warning: bad syntax, perhaps a bogus '-'? See /usr/share/doc/procps-3.2.8/FAQ
root     22988  146  0.2 642984 73976 ?        Sl   14:32  19:10 /usr/local/mongodb/bin/mongod --dbpath=/usr/local/mongodb/data/db --logpath=/usr/local/mongodb/logs/mongodb.log --fork
root     23242  0.0  0.0 105292   864 pts/2    S+   14:45   0:00 grep mongo
[root@cluster whatweb]# whatweb *** --log-mongo-database local --log-mongo-host 127.0.0.1 --log-mongo-collection whatweb --log-mongo-username=whatweb --log-mongo-password='pass' -p +./plugins-disabled/Charset.rb
/public/home/***/whatweb/lib/output.rb:653:in `initialize': uninitialized constant Mongo::Connection (NameError)
	from /public/home/***/whatweb/whatweb:879:in `new'
	from /public/home/***/whatweb/whatweb:879:in `<main>'

```
same situation.
<http://stackoverflow.com/questions/12511699/mongoid-uninitialized-constant-mongo-nameerror>
<http://stackoverflow.com/questions/30431059/uninitialized-constant-mongoconnection>

**Comment by urbanadventurer** [comment]
5
down vote
accepted
You are using the new Mongo 2.0 driver which breaks backwards compatibility with the 1.x series. The code you are trying is for the 1.x series.

You simply need to do

require 'mongo'
db = Mongo::Client.new([ '192.168.56.102:27017' ], :database => 'convoos')
Here is the tutorial for the 2.x version of the Ruby Mongo Driver.

**Comment by millette** [comment]
@urbanadventurer can you clarify please? I'm new to mongodb and really haven't used Ruby much in the last 5 years...

Is WhatWeb compatible with Mongo 2.x ?
Is the ruby Mongo driver version in sync with Mongo itself?

You hint at a tutorial, but the link is missing. Any help will be appreciated, thanks.

**Comment by millette** [comment]
Well, I found part of the answer I was looking for. In my case, gem install mongo installed v2 of the driver. I'm not using it for anything else, so I did the following:
```sh
$ sudo gem uninstall  mongo  --version 2.2.4
$ sudo gem install  mongo  --version 1.12.5
```

After fixing the driver version, WhatWeb worked as expected.

FYI I'm using Mongo 2.4.10 on Debian Stable (Jessie).
