### ISSUE TITLE
Error when running whatweb on kali linux 1.1.0a 

### ISSUE THREAD

**Issue by JufiantoHenri** [urbanadventurer/WhatWeb#169]
when i run whatweb site.com i have an error "/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will be deprecated in the future, use String#encode instead."
i have ruby 1.9.3p194 (2012-04-20 revision 35410) [i486-linux]

**Comment by urbanadventurer** [comment]
Fixed
