### ISSUE TITLE
Convert xml to html

### ISSUE THREAD

**Issue by glira** [urbanadventurer/WhatWeb#170]
I tried in many ways to convert xml to html using the xsl file, someone successful?
I always get several errors

**Comment by glira** [comment]
is a bug caused by various tags in xml like:
</log>
<log>
then we delete all and it works!

**Comment by urbanadventurer** [comment]
XML output renders correctly in Firefox. It is also parsed correctly with online parsers like http://codebeautify.org/xml-to-html-converter

You can convert the whatweb XML output to HTML using the standard xsltproc tool. This is available in most Linux distributions.

$ sudo apt-get install xsltproc
$ xsltproc  -o xml.html whatweb.xsl whatweblog.xml
