### ISSUE TITLE
MySQL log creation: "#1709 - Index column size too large"

### ISSUE THREAD

**Issue by netagence** [urbanadventurer/WhatWeb#180]
On a "default" Ubuntu install with _MySQL 5.5.49-0ubuntu0.14.04.1_, I get the following error when trying to create tables from the --log-sql-create option:

> # 1709 - Index column size too large. The maximum column size is 767 bytes.

The _plugins_ and _scans_ table are created ok, this is only related to the _targets_ table.
I am not a mysql expert enough to solve this, I found a few suggestions and ran
_
set global innodb_file_format = BARRACUDA;
set global innodb_large_prefix = ON_;

to no avail, and doing something I don't fully understand such as reducing a field size which may cause issues later does not seem the way to go.

I found the following hints

http://mechanics.flite.com/blog/2014/07/29/using-innodb-large-prefix-to-avoid-error-1071/
http://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes

Thanks !

**Comment by Code0x58** [comment]
I think the problem is because of the `UNIQUE` constraint on [target.targets](https://github.com/urbanadventurer/WhatWeb/blob/master/lib/output.rb#L1004), a `varchar(900)`, is implicitly creating an index, which is well over the limitation before considering the encoding.

**Comment by Code0x58** [comment]
I've added a simple patch for the problem, you can check it out or copy it by hand (spares adding a remove and it is only one number). Once you have done that it looks like you'll be able to just run with `--log-sql-create` and it will complete successfully.

**Comment by Code0x58** [comment]
I've realised that patch probably won't work because the unique constraint is on `target`+`status`, so the size of `target` will have to be under 255 as `status` is 10 chars. Reducing to 245 may not be low enough.

**Comment by urbanadventurer** [comment]
I agree with the discussion and have increased the target length to 2048, an older IE URL limit. What what I've read, you will need to use MySQL version 5.7 or later.
