### ISSUE TITLE
incompatible encoding regexp match 

### ISSUE THREAD

**Issue by chuangsheng** [urbanadventurer/WhatWeb#182]
Base:version 0.4.8. Unreleased 

 my plugin have chinese  string
 `{ :regexp=>/<title>[^<]*显然RUBY对编码并不友好[^<]*<\/title>/ },`
happend a error:`ERROR: Plugin chinese_test failed for http://www.mlaes.com/. incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)`

**Comment by urbanadventurer** [comment]
This worked for me with Ruby version 2.2.3.

**Comment by urbanadventurer** [comment]
Hi @chuangsheng could you share your new plugins on your private Github repository? I can convert them to the new plugin format for the 0.5.0-dev branch?

**Comment by chuangsheng** [comment]
I‘am very very sorry.
My project plugin is  private ，because  to my customer.

And，very sorry  2 years ago，I delete my github's project.   I can't  skilled use  git，I development my customer's plugin  post to github ....  so  I delete it.

Thanks  to your whatweb project .

Again sorry my poor English，It's very poor and bad......

**Comment by urbanadventurer** [comment]
These Chinese characters work for me.

```
Plugin.define do
	name "Chinese-character-test"

	# Matches #
	matches [
	{ :regexp=>/<title>[^<]*显然RUBY对编码并不友好[^<]*<\/title>/ },

	] 

end
```

**Comment by urbanadventurer** [comment]
I can match the title of baidu.com but further testing by native speaker would be helpful.
