### ISSUE TITLE
Error using HTTPs over proxy, version 0.4.8-dev

### ISSUE THREAD

**Issue by tmnar** [urbanadventurer/WhatWeb#183]
When trying to issue a whatweb request on a domain with https using a proxy, each request fails with the following output:
`whatweb --debug --proxy=<IP>:<PORT> https://<URL>`
`https://<URL> ERROR: undefined method join for #<String:<STRING>>`

I have verified this on multiple proxy services.

**Comment by rdubourguais** [comment]
Hi @tmnar, I just created a pull request that fix your issue. Tests would be appreciated ;)

**Comment by urbanadventurer** [comment]
Thanks @rdubourguais for fixing this. It works for me.
