### ISSUE TITLE
ERROR: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure

### ISSUE THREAD

**Issue by milo2012** [urbanadventurer/WhatWeb#184]
I encountered the below error when running WhatWeb on a website supporting only TLS1.0.

$ ./whatweb -a 3 https://vpn.xxx.com:443
https://vpn.xxx.com:443 ERROR: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure

$ nmap --script ssl-enum-ciphers -p 443 xxx.com
443/tcp open https
| ssl-enum-ciphers: 
| TLSv1.0: 
| ciphers: 
| TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
| compressors: 
| NULL
| cipher preference: indeterminate
| cipher preference error: Too few ciphers supported
|_ least strength: C

Please see https://github.com/milo2012/WhatWeb/commit/216317634877863070567c2bfbae81c081b6d91b for the fix i am implemented locally. I have tested this on Kali Linux.

Thank you for the awesome tool.

**Comment by urbanadventurer** [comment]
Thanks @milo2012
