### ISSUE TITLE
Improvement idea

### ISSUE THREAD

**Issue by wifiuk** [urbanadventurer/WhatWeb#194]
At the moment the output is like this

`http://google.com [302 Found] Country[UNITED STATES][US], IP[216.239.38.120], RedirectLocation[http://www.google.co.uk/?gfe_rd=cr&ei=wENJWJbuKfLW8gfEuo3IAQ], Title[302 Moved], Via-Proxy[1.1 Squid (squid/3.2.14)], X-Cache[Squid]
http://www.google.co.uk/?gfe_rd=cr&ei=wENJWJbuKfLW8gfEuo3IAQ [200 OK] Cookies[NID], Country[UNITED STATES][US], HTML5, HTTPServer[gws], HttpOnly[NID], IP[216.239.38.120], Script, Title[Google], Via-Proxy[1.1 Squid (squid/3.2.14)], X-Cache[Squid], X-Frame-Options[SAMEORIGIN], X-XSS-Protection[1; mode=block]
`

would it be better to have it like this?

http://google.com [302 Found] 
Country[UNITED STATES][US],
 IP[216.239.38.120], 
RedirectLocation[http://www.google.co.uk/?gfe_rd=cr&ei=wENJWJbuKfLW8gfEuo3IAQ], 
Title[302 Moved], 
Via-Proxy[1.1 Squid (squid/3.2.14)], 
X-Cache[Squid]
http://www.google.co.uk/?gfe_rd=cr&ei=wENJWJbuKfLW8gfEuo3IAQ [200 OK] Cookies[NID], 
Country[UNITED STATES][US], 
HTML5, 
HTTPServer[gws], 
HttpOnly[NID], 
IP[216.239.38.120], 
Script, Title[Google], 
Via-Proxy[1.1 Squid (squid/3.2.14)], 
X-Cache[Squid], X-Frame-Options[SAMEORIGIN], 
X-XSS-Protection[1; mode=block]

**Comment by bcoles** [comment]
I agree, it's more readable when scanning a small number of URLs.

CSV output is more more easily grepable.

**Comment by wifiuk** [comment]
could maybe have an option -c or something for --csv-output

**Comment by urbanadventurer** [comment]
The output from -v might be better.

<img width="882" alt="image" src="https://user-images.githubusercontent.com/101783/33127675-c96ed172-cf89-11e7-9c7b-115d1289ed2e.png">
