### ISSUE TITLE
grep not working, custom google dorks

### ISSUE THREAD

**Issue by sanyiofugh** [urbanadventurer/WhatWeb#196]
Hi!

Hoe exactly the grep feature is working? I have tried _--grep keyword_ and its not working for me :(

As well, how can I send a custom google dorks search with whatweb? for example _--dorks error_

Thanks!

**Comment by bcoles** [comment]
The `--grep STRING` option allows you to search for `STRING` in HTTP responses. If the string is found, the `Grep` plugin is returned as a match.

For example:

```console
$ ./whatweb whatweb.net --grep whatweb
http://whatweb.net [200 OK] Apache, Country[UNITED STATES][US], Grep, HTTPServer[Apache], IP[65.181.113.51], Script[text/javascript], Title[WhatWeb - Next generation web scanner.], UncommonHeaders[x-content-type-options], X-Frame-Options[sameorigin], X-XSS-Protection[1; mode=block]

$ ./whatweb whatweb.net --grep stringdoesnotexist
http://whatweb.net [200 OK] Apache, Country[UNITED STATES][US], HTTPServer[Apache], IP[65.181.113.51], Script[text/javascript], Title[WhatWeb - Next generation web scanner.], UncommonHeaders[x-content-type-options], X-Frame-Options[sameorigin], X-XSS-Protection[1; mode=block]
```

Regarding your Google dorks query, I'm not entirely sure what you mean. You may want to check out the [Hunter addon for WhatWeb](https://github.com/urbanadventurer/WhatWeb/blob/master/addons/hunter) which [searches Google for the specified google dork, then scans the results with WhatWeb](https://www.youtube.com/watch?v=LtEKTMi79ug).

**Comment by urbanadventurer** [comment]
This is working. So I'll close the issue.

**Comment by urbanadventurer** [comment]
I've changed the behaviour to be more like what you'd expect with only results that have the grep plugin being included in the output.

**Comment by urbanadventurer** [comment]
It's in the 0.5.0-dev branch
