### ISSUE TITLE
Struts

### ISSUE THREAD

**Issue by lovebair2022** [urbanadventurer/WhatWeb#198]

**Comment by lovebair2022** [comment]
Is there a plugin of struts2?

**Comment by Code0x58** [comment]
Listing the plugins shows there is one for Apache Structs, reading the code shows the plugin has a pattern for version 1 and 2.

**Comment by urbanadventurer** [comment]
Hi @lovebair2022. This is how to search plugins for the term 'struts'.

<img width="733" alt="image" src="https://user-images.githubusercontent.com/101783/33125757-0c170d8a-cf82-11e7-9735-b7d13dc7d76f.png">

You can read the plugin code in plugins/apache-struts.rb to see how it works. It has the following patterns.

<img width="997" alt="image" src="https://user-images.githubusercontent.com/101783/33125844-7a84339c-cf82-11e7-96b9-bba7c988f83d.png">

**Comment by AgoraSecurity** [comment]
Hello,

I found 0 results in Shodan for "org.apache.struts" and I've found a couple of websites using Struts that doesn't get triggered by the plugin.

Do you know if there are other ways to fingerprint Struts?

**Comment by urbanadventurer** [comment]
Sorry I don't know but if you find out then please let us know so we can built it into the plugin.

**Comment by secureli** [comment]
I'd be happy to help out with this.

**Comment by AgoraSecurity** [comment]
I've been searching for a while, but I haven't found a reliable method.
