### ISSUE TITLE
Can't run WhatWeb on Windows 7

### ISSUE THREAD

**Issue by Bobin56** [urbanadventurer/WhatWeb#206]
Hello . I have downloaded the zip and extracted to c://whatweb . When i run in the console i get an error "'whatweb' is not recognized as an internal or external command, operable program or batch file. " . I have already installed ruby 1.8.7 and DevKit . what could be wrong ? please help.

**Comment by urbanadventurer** [comment]
This seems like a ruby environment issue. 
The fastest way to get up and running with WhatWeb is to download a Kali Linux virtual machine that you can run within VirtualBox or VMWare.
