### ISSUE TITLE
invalid multibyte escape on Zorin OS 12.1 (there is a problem !)

### ISSUE THREAD

**Issue by wathiq-iq** [urbanadventurer/WhatWeb#208]
wathiq@beez:~$ whatweb
/usr/bin/whatweb: /usr/lib/ruby/vendor_ruby/rchardet/universaldetector.rb:39: invalid multibyte escape: /[\x80-\xFF]/ (SyntaxError)

Base System: Zorin OS 12.1 32-bit

**Comment by urbanadventurer** [comment]
What version of ruby are you running?

**Comment by urbanadventurer** [comment]
Need to upgrade rchardet gem to a version released since 2014. See #248.
