### ISSUE TITLE
Patches for 3 errors (ubuntu 16.04 and + etc)

### ISSUE THREAD

**Issue by ZEROF** [urbanadventurer/WhatWeb#211]
Here you can find the list of fix i used to make whatweb run again without any output errors or warnings. I will not provide patch to fix encoding error, because all what you need to do is to update your ruby gems.

Dry run

Patch1

sudo patch --dry-run -p1 /usr/share/whatweb/lib/tld.rb tld_patch (this is how you can test all pathces)

If no errors

sudo patch -p1 /usr/share/whatweb/lib/tld.rb tld_patch

Patch2

sudo patch -p1 /usr/share/whatweb/plugins/wordpress.rb wordpress_ruby_patch

Patch3

sudo patch -p1 /usr/share/whatweb/lib/extend-http.rb extend_http_patch

In the end (that is what i call sexy and fixed :))
![image](https://user-images.githubusercontent.com/2687905/28248692-ed0055c6-6a48-11e7-9233-fd091b7462b2.png)

Patch download:

[all_patches.zip](https://github.com/urbanadventurer/WhatWeb/files/1151095/all_patches.zip)

**Comment by urbanadventurer** [comment]
Thanks @ZEROF.

By the time I got to your patches the Timeout extend-http issue was already fixed. 

Thanks for sending these patches but unfortunately they didn't get merged.
