### ISSUE TITLE
uninitialized constant Mongo::Connection (NameError)

### ISSUE THREAD

**Issue by xl7dev** [urbanadventurer/WhatWeb#212]
$ mongo --version
MongoDB shell version v3.4.6
git version: c55eb86ef46ee7aede3b1e2a5d184a7df4bfb5b5
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1604
    distarch: x86_64
    target_arch: x86_64
$ ruby --version
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
$ ./whatweb www.baidu.com --log-mongo-host 127.0.0.1 --log-mongo-database web --log-mongo-collection whatweb -p +./plugins-disabled/charset.rb
/home/test/tool/WhatWeb/lib/output.rb:861:in `initialize': uninitialized constant Mongo::Connection (NameError)
Did you mean?  Mongo::Collection
	from ./whatweb:963:in `new'
	from ./whatweb:963:in `<main>'

**Comment by urbanadventurer** [comment]
I've updated whatweb for Mongo version 2.x. This will work now.

**Comment by xl7dev** [comment]
👍
