### ISSUE TITLE
I want to use PHP to call whatweb

### ISSUE THREAD

**Issue by imlhb** [urbanadventurer/WhatWeb#249]
hi,whatweb
I want to use PHP to call whatweb.
I want to make a web site to use whatweb
I use php funtion of exec,but Error.
`

  | <br>$o:<br>array(15) {
-- | --
  | [0]=>
  | string(113) "/usr/share/rubygems/rubygems/path_support.rb:68:in `path=': undefined method `+' for nil:NilClass (NoMethodError)"
  | [1]=>
  | string(69) "	from /usr/share/rubygems/rubygems/path_support.rb:30:in `initialize'"
  | [2]=>
  | string(50) "	from /usr/share/rubygems/rubygems.rb:357:in `new'"
  | [3]=>
  | string(52) "	from /usr/share/rubygems/rubygems.rb:357:in `paths'"
  | [4]=>
  | string(51) "	from /usr/share/rubygems/rubygems.rb:379:in `path'"
  | [5]=>
  | string(65) "	from /usr/share/rubygems/rubygems/specification.rb:796:in `dirs'"
  | [6]=>
  | string(72) "	from /usr/share/rubygems/rubygems/specification.rb:660:in `each_normal'"
  | [7]=>
  | string(65) "	from /usr/share/rubygems/rubygems/specification.rb:671:in `_all'"
  | [8]=>
  | string(65) "	from /usr/share/rubygems/rubygems/specification.rb:824:in `each'"
  | [9]=>
  | string(65) "	from /usr/share/rubygems/rubygems/specification.rb:866:in `find'"
  | [10]=>
  | string(82) "	from /usr/share/rubygems/rubygems/specification.rb:866:in `find_inactive_by_path'"
  | [11]=>
  | string(59) "	from /usr/share/rubygems/rubygems.rb:175:in `try_activate'"
  | [12]=>
  | string(88) "	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'"
  | [13]=>
  | string(78) "	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:144:in `require'"
  | [14]=>
  | string(47) "	from <internal:abrt_prelude>:2:in `<compiled>'"
  | }
  | <br>$e:<br>int(1)

`

my php code:
`<?php 

header("Content-type: text/html; charset=utf-8");
$url = 'www.lhbbk.com';
// $url = $_GET['url'];
// print(exec('./whatweb'.$url));
$a = exec('whatweb/whatweb '.$url.' 2>&1',$o,$e);

echo '<br>$o:<br>';
var_dump($o);
echo '<br>$e:<br>';
var_dump($e);

?>`

**Comment by urbanadventurer** [comment]
This is a problem with the environment of PHP or Ruby environment. I tested your code and it works for me.

```
$o:
array(2) {
  [0]=>
  string(516) "http://www.lhbbk.com [301 Moved Permanently] Country[CHINA][CN], HTTPServer[Tengine], IP[220.181.105.153], PoweredBy[Tengine], RedirectLocation[https://www.lhbbk.com/], Tengine-Web-Server, Title[301 Moved Permanently], UncommonHeaders[timing-allow-origin,eagleid], Via-Proxy[kunlun2.cn171[,0]]"
  [1]=>
  string(951) "https://www.lhbbk.com/ [200 OK] Country[CHINA][CN], HTML5, HTTPServer[Tengine], IP[220.181.105.153], JQuery, MetaGenerator[Typecho 1.1/17.10.30], PHP[5.6.30], PasswordField[password], Script[text/javascript,text/template], Tengine-Web-Server, Title[刘泓宾博客 - 分享知识和见解], UncommonHeaders[x-swift-savetime,x-swift-cachetime,timing-allow-origin,eagleid], Via-Proxy[cache13.l2nu20-3[334,200-0,M], cache47.l2nu20-3[335,0], kunlun8.cn125[408,200-0,M], kunlun4.cn125[446,0]], X-Powered-By[PHP/5.6.30], X-UA-Compatible[IE=edge], x-pingback[https://www.lhbbk.com/action/xmlrpc]"
}

$e:
int(0)
```

**Comment by imlhb** [comment]
I also think is my PHP or Ruby environment.
but I don't kown the problem how to solve.
I have other server use “whatweb-0.4.7”，this can successful.

**Comment by imlhb** [comment]
I hope you can make a PHP program, because I want to make this a website, or provide an API interface,please.

**Comment by bcoles** [comment]
You may enjoy https://whatweb.net/
