### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by T4P4N** [urbanadventurer/WhatWeb#250]
![screenshot_2018-04-17-10-20-30-528_com termux](https://user-images.githubusercontent.com/32695903/38849684-f9c4c250-422a-11e8-9454-e03a67f9465b.png)

**Comment by Edu4rdSHL** [comment]
Hello, @T4P4N. It's a specific Termux issue, not a whatweb issue. Anyways if you want to solve that execute it command:

`touch $PREFIX/etc/hosts`

**Comment by T4P4N** [comment]
Thank You Very Much @Edu4rdSHL

**Comment by stofstar** [comment]
thanks
