### ISSUE TITLE
Unable to log to elastic search 6.x

### ISSUE THREAD

**Issue by rhodejo** [urbanadventurer/WhatWeb#251]
```
$ ./WhatWeb/whatweb 127.0.0.1 --log-elastic-host 127.0.0.1:9200 
http://127.0.0.1 ERROR: Connection refused - connect(2) for "127.0.0.1" port 80
http://127.0.0.1 [ Unassigned] 

406 Not Acceptable
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
```

Apparently this was introduced last year when elasticsearch 6.0 was released: https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests

Is there any workaround or can whatweb be updated to work with elasticsearch 6.x

**Comment by urbanadventurer** [comment]
Same as closed issue #253
