### ISSUE TITLE
Output for elasticsearch v6+

### ISSUE THREAD

**Issue by superhuahua** [urbanadventurer/WhatWeb#253]
when I want to save result for elastic stack, I use `./whatweb [host]--log-elastic-host=localhost:9200` , but I get error message:

> {"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}

According to the message, edit file `lib/output.rb` and add `req.add_field('Content-Type', 'application/json')` in line 960 of the file will fix this error.

**Comment by urbanadventurer** [comment]
Thanks @superhuahua for reporting this issue and providing a fix.
