### ISSUE TITLE
Add script initialization to executable file.

### ISSUE THREAD

**Issue by Edu4rdSHL** [urbanadventurer/WhatWeb#256]
Please, add `#!/usr/bin/bash` to the executable file placed in /usr/bin/whatweb, if you try to execute it from python usiing subprocess.call it gives a OSError.

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shl/Github/webhackshl/modules/fingerwebmod.py", line 39, in whatw
    call(["whatweb","-v", web])
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'whatweb'
`
It's solved adding the line in the script top and also is a good programming technique.

**Comment by urbanadventurer** [comment]
The executable file is not a shell script in a default WhatWeb installation.

Please tell me what OS you are using and what package manager was used to install WhatWeb.

The first line of the whatweb executable should be:
```
#!/usr/bin/env ruby
```

**Comment by Edu4rdSHL** [comment]
@urbanadventurer it's a specific distribution, i think. I'm using ArchLinux with blackarch repos.

**Comment by bcoles** [comment]
As @urbanadventurer suggests, WhatWeb already has a shebang line in the executable script.

Here's the relevant [build script](https://github.com/BlackArch/blackarch/blob/master/packages/whatweb/PKGBUILD), which creates a shell script wrapper for WhatWeb. Looks like it was fixed on May 2.

If the patch on May 2 didn't fix the issue, then this will need to be resolved by whoever is managing the BlackArch WhatWeb package.

Closing this issue.

**Comment by Edu4rdSHL** [comment]
It create a /usr/bin/whatweb file but it doesnt start with #!/usr/bin/env bash or #!/usr/bin/bash, because it python fails.

**Comment by bcoles** [comment]
Reported to BlackArch as per above.

**Comment by bcoles** [comment]
Allegedly this has now been fixed in BlackArch repos.
