### ISSUE TITLE
Empty output using whatweb in ruby versions >= 2.5.*

### ISSUE THREAD

**Issue by Edu4rdSHL** [urbanadventurer/WhatWeb#257]
Steps to reproduce, clone the latest Whatweb version, try executing it with a ruby version >= 2.5.* for scanning a site under https. Executing whatweb with a minor ruby version fix the issue.

Please check the next video.

<a href="https://asciinema.org/a/dpiFbJm6mJ5a14H1qtcPlMtbT" target="_blank"><img src="https://asciinema.org/a/dpiFbJm6mJ5a14H1qtcPlMtbT.png" /></a>

**Comment by urbanadventurer** [comment]
This works for me with Ruby 2.5.1 in both branches.  
Does it work if you run ```bundle install```?

**Comment by Edu4rdSHL** [comment]
Gems are installed, still having the issue.

<a href="https://asciinema.org/a/0LRmV4yLrLyhS5svZj8EzUW1S" target="_blank"><img src="https://asciinema.org/a/0LRmV4yLrLyhS5svZj8EzUW1S.png" /></a>

**Comment by urbanadventurer** [comment]
Did you figure out what was wrong?
