### ISSUE TITLE
Security Issue: Stored XSS

### ISSUE THREAD

**Issue by ehaoxiongdiycw** [urbanadventurer/WhatWeb#261]
When I used WhatWeb to scan a target and use `--log-json` option, stored XSS may occur.

The target just like this:

```php
<?php
header("Location: /whatweb/xss/<script>alert(/xss/)</script>/");
die();
```

I used KaliLinux with WhatWeb v0.4.9:

```bash
root@kali:~# whatweb -v 'http://localhost/whatweb.php' --log-json=whatweb.json
```

And the result:

```json
[{"target":"http://localhost/whatweb.php","http_status":302,"request_config":{"headers":{"User-Agent":"WhatWeb/0.4.9"}},"plugins":{"X-Powered-By":{"string":["PHP/5.5.9-1ubuntu4.25"]},"PHP":{"version":["5.5.9-1ubuntu4.25"]},"Apache":{"version":["2.4.7"]},"Country":{"string":["RESERVED"],"module":["ZZ"]},"IP":{"string":["localhost"]},"HTTPServer":{"os":["Ubuntu Linux"],"string":["Apache/2.4.7 (Ubuntu)"]},"RedirectLocation":{"string":["/whatweb/xss/<script>alert(/xss/)</script>/"]}}},
```

When I use Windows7 with IE7 open the result, XSS has been triggered.

<img width="597" alt="2018-08-26 21 54 45" src="https://user-images.githubusercontent.com/7035940/44635274-bf745300-a9d5-11e8-92ba-24bc4a669a36.png">

Suggestion:
Use url encode for the output url. `<script>alert(/xss/)</script>` will be convert to `%3Cscript%3Ealert%28/xss/%29%3C/script%3E`.

Discovered by fobcrackgp@163.com

**Comment by barf** [comment]
Unable to reproduce on current versions of Chromium or Firefox. 

I think this only affects users of unsupported or out-of-date web browsers (IE6 and IE7) and operating systems (Windows 7). 

The chosen test environment is not indicative of fault in the application, it requires a bug in the browser to reproduce (not respecting Content-Type in HTTP headers and file extension not respected).

**Comment by ehaoxiongdiycw** [comment]
Yes, this fault only affects in IE6 and IE7. 

And there is a Exception when WhatWeb parse the redirect URL like ` /whatweb/xss/<script>alert(/xss/)</script>/`. I think you have found it.
