### ISSUE TITLE
installation on Mac

### ISSUE THREAD

**Issue by ghost** [urbanadventurer/WhatWeb#275]
Hello, I followed the instructions but can't get it installed. Ruby and dependencies are correctly installed. But I don't get Whatweb installed. Right now the files are downloaded on my macbook. Can you instruct me which commands lines to follow to install the download?

**Comment by urbanadventurer** [comment]
WhatWeb works on a Macbook but installation using the `make install` command does not.

**Comment by urbanadventurer** [comment]
@ghost I have fixed this issue now. Let me know if it doesn't work for you.
