### ISSUE TITLE
Please make a tagged release 0.5.0

### ISSUE THREAD

**Issue by sbrun** [urbanadventurer/WhatWeb#280]
Hello,

Please make a tagged for the latest version 0.5.0. It's easier for packager to monitor the new releases and to package.

Thanks.

**Comment by abenson** [comment]
It's been 2 years and 400+ commits since the last tag.

**Comment by urbanadventurer** [comment]
I've tagged version 0.5.0
https://github.com/urbanadventurer/WhatWeb/releases/tag/v0.5.0
