### ISSUE TITLE
weird output format

### ISSUE THREAD

**Issue by Fabre-Pierre-jean** [urbanadventurer/WhatWeb#290]
Hi,
I dont know if it is the new output format but for what i've seen, that's not normal format:
![image](https://user-images.githubusercontent.com/54306081/73589664-ae3c4980-44d9-11ea-8ad1-aec61ecbb354.png)
i have no errors or whatever, just this output.
Thanks in advance :)

**Comment by urbanadventurer** [comment]
Hi @Fabre-Pierre-jean 

This is the brief format and it is meant to have one URL on a single line so it can be used with tools like grep. The output format looks normal to me except for the fancy terminal font.

If you add -v to your scan you can see the Verbose output.
