### ISSUE TITLE
windows system using mongodb exception

### ISSUE THREAD

**Issue by cangqingzhe** [urbanadventurer/WhatWeb#295]
whatweb:578:in `<main>': uninitialized constant OutputMongo

**Comment by cangqingzhe** [comment]
After my test, it can be used normally in version 0.4.9, and this exception will appear in version 0.5.1
![image](https://user-images.githubusercontent.com/32150850/74079963-4eb1e100-4a79-11ea-96eb-c3113eaee9b5.png)

**Comment by urbanadventurer** [comment]
Try the latest version. This issue was fixed in #293
