### ISSUE TITLE
URI.escape is obsolete

### ISSUE THREAD

**Issue by xambroz** [urbanadventurer/WhatWeb#308]
Hello,
when executing whatweb 0.5.1 on Fedora 32 (ruby 2.7.0+) I see always the messasge that URI.escape is obsolete:

$ whatweb https://example.com
**/usr/share/whatweb/lib/target.rb:188: warning: URI.escape is obsolete**
https://example.com [200 OK] Country[EUROPEAN UNION][EU], HTML5, HTTPServer[ECS (dcb/7EEA)], IP[93.184.216.34], Title[Example Domain]

**Comment by Trio-Musketeers** [comment]
The Same issue with me, did u figure any fix for it @xambroz ?

**Comment by urbanadventurer** [comment]
This is already fixed in the master branch. I'll release an updated version soon.
