### ISSUE TITLE
JSON Logging fails with message Can't convert to UTF-8 can't modify frozen String

### ISSUE THREAD

**Issue by definity** [urbanadventurer/WhatWeb#311]
Running whatweb on the url `accu-chek.co.kr` with aggression level 3 `-a 3` and JSON logging `--log-json=test.json`  results in the following error.
`ERROR Logging failed: https://accu-chek.co.kr/ - Can't convert to UTF-8 can't modify frozen String`

![whatweb_error](https://user-images.githubusercontent.com/4111455/84387114-cbed8e00-abf2-11ea-847c-f67ddfa5df03.png)

The error is not thrown with aggression level 1 `-a 1`.
Running the latest version of WhatWeb 0.5.2 with bundles installed/updated from Google Cloud Shell.

**Comment by Cherry552** [comment]
> Ejecutar whatweb en la url `accu-chek.co.kr`con nivel de agresión 3 `-a 3`y el registro JSON `--log-json=test.json` da como resultado el siguiente error.
> `ERROR Logging failed: https://accu-chek.co.kr/ - Can't convert to UTF-8 can't modify frozen String`
> 
> ![whatweb_error](https://user-images.githubusercontent.com/4111455/84387114-cbed8e00-abf2-11ea-847c-f67ddfa5df03.png)
> 
> El error no se produce con el nivel de agresión 1 `-a 1`.
> Ejecutando la última versión de WhatWeb 0.5.2 con paquetes instalados / actualizados desde Google Cloud Shell.
