### ISSUE TITLE
Get Request information for Detection

### ISSUE THREAD

**Issue by Phylu** [urbanadventurer/WhatWeb#344]
Sometimes I am struggling to retrieve the information, which part of a plugin is responsible for a successful fingerprint. E.g. A certain Tomcat Version was detected, I cannot be sure if it was on the Main page or a random error page. What I need to do to retrieve that information is opening the plugin file manually to check where there was a match.

Is there any way to simplify this process?

In an optimal world, I would have the option to see which Request was responsible for getting the information and how it was retrieved from the response.

(I would be happy to tackle the issue if I get some pointers of how to implement it if needed.)

**Comment by bcoles** [comment]
You can use `-vv` for more verbose output. Although it is not easily parsable. This will list the matches.

**Comment by Phylu** [comment]
Thanks a lot. Did not see the double verbose yet. I will try to work with it.
