### ISSUE TITLE
Consider not to specify the color of the output font?

### ISSUE THREAD

**Issue by PumpkinCheshire** [urbanadventurer/WhatWeb#345]
Sorry, I used the light theme terminal, so the output is like this.
![Screenshot_20201104_210723](https://user-images.githubusercontent.com/30663626/98098182-1d6c2180-1ee2-11eb-8944-1c716b419581.png)
This led me to think that some of my packages or fonts were abnormal. After a long time of inspection, I realized that some fonts were output in pure white. The problem was solved after replacing it with a black background. It is recommended not to specify the color of the output font, let the terminal to decide.

**Comment by urbanadventurer** [comment]
Pull the latest version from the master branch. It's fixed.
