### ISSUE TITLE
favicon.ico Error in MD5 calculation

### ISSUE THREAD

**Issue by winezer0** [urbanadventurer/WhatWeb#370]
for example  http://172.120.6.96:9999/favicon.ico 

pp @md5sum result is "3c525d9a513fc9806cc66b01420d1dfe"

but actually file md5 sum result it should be "0488faca4c19046b94d07c3ee83cf9d6"

**Comment by bcoles** [comment]
Looks like this is due to UTF-8 conversion.

Commenting out this line causes the MD5sum to be calculated correctly:

https://github.com/urbanadventurer/WhatWeb/blob/ae899862c5acb1f73227bd5d64fb081024b39520/lib/target.rb#L313

**Comment by winezer0** [comment]
Thank you very much, the problem has been resolved
