### ISSUE TITLE
Error when installing it in MacOS using `sudo make install`

### ISSUE THREAD

**Issue by Fayxx** [urbanadventurer/WhatWeb#387]
upgrade/installation will leave the my-plugins folder
rm -Rf /usr/bin/whatweb /usr/share/man/man1/whatweb.1 /usr/share/man/man1/whatweb.1.gz /usr/share/doc/whatweb /usr/share/whatweb/plugins-disabled /usr/share/whatweb/plugins /usr/share/whatweb/lib /usr/share/whatweb/plugin-development /usr/share/whatweb/addons
install -d /usr/share/man/man1
install: chmod 755 /usr/share/man/man1: Operation not permitted
install -p  -m 644 whatweb.1 /usr/share/man/man1/whatweb.1
install: /usr/share/man/man1/whatweb.1: Operation not permitted
make: *** [install] Error 71

**Comment by bcoles** [comment]
Leaving the `my-plugins` directory is intentional. This prevents deleting custom plugins.

**Comment by Fayxx** [comment]
And what can I do to install WhatWeb anyways?

**Comment by bcoles** [comment]
On Linux/OSX: `make install`

See also: https://github.com/urbanadventurer/WhatWeb/wiki/Installation

**Comment by Fayxx** [comment]
As I have already mentioned, this is where the error came from. I am looking for a fix to that.
